# -*- coding: utf-8 -*-
"""breast_cancer_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14TQvenGYnmP93uFKeRHIRX3-KZSjNf_Y

1. Import Libraries
"""

# Data handling
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Dataset
from sklearn.datasets import load_breast_cancer

# Preprocessing
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_classif

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Evaluation
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    RocCurveDisplay,
    PrecisionRecallDisplay
)

"""2. Load Dataset"""

data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target)

print("Shape:", X.shape)
print(X.head())
print("Target classes:", data.target_names)

"""3. Exploratory Data Analysis (EDA)"""

sns.countplot(x=y)
plt.title("Class Distribution")
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(X.corr(), cmap="coolwarm")
plt.title("Feature Correlation")
plt.show()

X.hist(figsize=(14,10))
plt.tight_layout()
plt.show()

"""4. Train Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""5. Feature Selection"""

selector = SelectKBest(score_func=f_classif, k=10)

X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

"""6. Machine Learning Pipelines"""

pipelines = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=5000))
    ]),

    "Random Forest": Pipeline([
        ("scaler", StandardScaler()),
        ("model", RandomForestClassifier())
    ]),

    "SVM": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC(probability=True))
    ])
}

"""7. Train Models"""

for name, pipe in pipelines.items():
    pipe.fit(X_train_selected, y_train)
    print(name, "trained")

"""8. Cross Validation"""

cv_results = {}

for name, pipe in pipelines.items():
    scores = cross_val_score(pipe, X_train_selected, y_train, cv=5)
    cv_results[name] = scores.mean()

print("Cross Validation Scores:")
print(cv_results)

"""9. Hyperparameter Tuning (Random Forest)"""

param_grid = {
    "model__n_estimators": [100, 200],
    "model__max_depth": [None, 10, 20]
}

grid = GridSearchCV(
    pipelines["Random Forest"],
    param_grid,
    cv=5
)

grid.fit(X_train_selected, y_train)

best_rf = grid.best_estimator_
print("Best parameters:", grid.best_params_)

"""10. Model Evaluation"""

models_to_evaluate = {
    "Logistic Regression": pipelines["Logistic Regression"],
    "Random Forest Tuned": best_rf,
    "SVM": pipelines["SVM"]
}

results = {}

for name, model in models_to_evaluate.items():
    preds = model.predict(X_test_selected)
    prob = model.predict_proba(X_test_selected)[:,1]

    results[name] = roc_auc_score(y_test, prob)

    print("Model:", name)
    print(classification_report(y_test, preds))
    print("ROC AUC:", results[name])
    print("------")

"""11. Model Comparison Table"""

comparison = pd.DataFrame(results.items(), columns=["Model", "ROC AUC"])
print(comparison)

"""12. Confusion Matrix + ROC + PR Curve"""

best_model = best_rf
preds = best_model.predict(X_test_selected)

cm = confusion_matrix(y_test, preds)
sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.show()

RocCurveDisplay.from_estimator(best_model, X_test_selected, y_test)
plt.show()

PrecisionRecallDisplay.from_estimator(best_model, X_test_selected, y_test)
plt.show()

"""13. Model Interpretation"""

importances = best_rf.named_steps["model"].feature_importances_
selected_features = X.columns[selector.get_support()]

importance_df = pd.DataFrame({
    "Feature": selected_features,
    "Importance": importances
}).sort_values("Importance", ascending=False)

print(importance_df)

sns.barplot(data=importance_df, x="Importance", y="Feature")
plt.title("Feature Importance")
plt.show()